---

- name: Add hostname env var into service
  ansible.builtin.shell:
    cmd: echo "HOST=$(cat /etc/hostname)" > .env
    chdir: ./promtail/

- name: Ensure .env file exists
  ansible.builtin.file:
    path: ./promtail/.env
    state: file

- name: Run Docker Compose DOWN Command
  ansible.builtin.command: docker-compose down
  args:
    chdir: ./promtail/

- name: Run Docker Compose UP Command
  ansible.builtin.command: docker-compose up -d
  args:
    chdir: ./promtail/